### ISSUE TITLE
.reset-text() undefined

### ISSUE THREAD

**Issue by Alan-Nugent** [USPTO/designpatterns#110]
I am finding that when compiling the LESS that '.reset-text' is undefined in '_tooltip.less'. I have searched the entire design pattern structure and cannot find an actual mixin function. This is causing the compilation to break.

**Comment by bmathews** [comment]
@Alan-Nugent  `.reset-text` is a newer mixin in Bootstrap. Try running `bower update` command from the project root to get the latest version from the `bower.json`.

**Comment by Alan-Nugent** [comment]
@bmathews Do you know if this is available on 3.3.4?

**Comment by bmathews** [comment]
@Alan-Nugent It landed in Bootstrap v3.3.5. The usptostrap css library is using v3.3.6.

**Comment by Alan-Nugent** [comment]
@bmathews Thanks for the quick response. I am marking the change now. Thanks.

**Comment by bmathews** [comment]
:+1: No problem!
