### ISSUE TITLE
Using bower to install the library

### ISSUE THREAD

**Issue by noonkay** [USPTO/designpatterns#124]
**Issue:** I'm using bower to install the USPTO pattern library but in addition to the stylesheets and the scripts, I end up pulling the docs, resources, downloads, etc -- basically the entire source code for the website -- into my project which is less than ideal. 

**Ask:** Can you please modify your `bower.json` to include `main` and/or `ignore` specifications so that a bower install doesn't pull the entire repo into the bower components folder?

**Comment by scottmerker** [comment]
@noonkay I'm wondering if you could elaborate a little further on your request?

Bower should only be pulling in 6 components.  

Cloning the repo you will get you everything (all of the source, documentation, all 350+meg of it).  We also offer just the main release .zip file (here: https://github.com/USPTO/designpatterns/releases) which includes only the css, svg icons, and the less files.

**Comment by noonkay** [comment]
Hi @scottmerker! 

Right. Bower pulls only the 6 additional dependencies. But I'd like to use Bower to pull your design library too, as is suggested in your [documentation](http://uspto.github.io/designpatterns/). I prefer not to use the zip file and have bower manage all the third party code. 

I believe because your `bower.json` doesn't specify what folders to [ignore](https://github.com/bower/spec/blob/master/json.md#ignore) and what files to use as [entry points](https://github.com/bower/spec/blob/master/json.md#main), when I use bower to install the library the repo is cloned in its entirety into the components folder. 

If this doesn't sound right to you, could you please explain what the documentation is referencing when it says the library could be downloaded via bower? Thanks!

**Comment by scottmerker** [comment]
Thoughts @bmathews ?

**Comment by bmathews** [comment]
Yeah it's a good idea. I'll send a PR in a second.

**Comment by scottmerker** [comment]
Thanks @bmathews!

**Comment by bmathews** [comment]
@scottmerker no problem!

@noonkay Let us know if you have any issues with the changes, or suggestions based on how you're using it. It'd probably be worth specifying a tag or commit sha for the dependency, if you're not already!
