### ISSUE TITLE
Browser Support

### ISSUE THREAD

**Issue by travisperson** [USPTO/designpatterns#140]
I was wondering if there is an official listed set of browser that this project supports, or aims to support.

**Comment by arvalarva** [comment]
Hello,

·        Browsers – All future websites and applications must be developed to support Web browsers that generate 5% of all visitor traffic.
Our April statistics dictate these our officially supported browsers:
Windows desktop using Internet Explorer 11+
Windows desktop using Chrome 49+
Windows desktop using Firefox 45+
iOS using Safari 9+
We aim to be compatible with the native Android browser and Apple desktop with Safari 9+ as well. The majority of our users use Apple iPhone, Apple iPad, and Samsung Galaxy, with the greatest mobile majority using Apple iOS devices.
Thanks,
Arva

**Comment by travisperson** [comment]
Thanks!
