### ISSUE TITLE
SASS Port

### ISSUE THREAD

**Issue by nicholas-b-carter** [USPTO/designpatterns#141]
Hi,

I was wondering if you ever considered a sass port of your library? I have started one but didn't know if this had already been done? Seems pretty straight forward?

**Comment by scottmerker** [comment]
@nicholas-b-carter -- I've been considering this, but definitely tentative to create a port due to the coming release of Bootstrap 4 (which uses SASS primarily).  Realistically, we won't update the codebase to BS4 until it at least has an official release, for obvious reasons.  I see us overhauling the library at that time, and switching stuff up a bit: switch to gulp (instead of grunt), port everything to SASS, etc.

If you are willing to contribute your SASS port now, that would be awesome, and I think valuable to the repo as a whole.

**Comment by nicholas-b-carter** [comment]
@scottmerker , No problem. It looks like that will be the direction I am taking in the mean time. I would be more than happy to contribute to this project 👍 Should I just issue a PR once I am finished?

**Comment by nicholas-b-carter** [comment]
@scottmerker , on that same note would you be opposed to me switching to gulp? or would you prefer I just push the sass port before the conversion to gulp?

**Comment by scottmerker** [comment]
@nicholas-b-carter for the sake of consistency, we'll stick with grunt for the time being;  I don't want to switch that mid-major version.  We'll still want to compile with LESS for now, but can offer SASS as an option.  Not sure if that makes sense:  some projects that are on-going wouldn't be able to quickly switch processors (and i don't think we would want to suddenly swap them).

**Comment by nicholas-b-carter** [comment]
@scottmerker , no problem thats why i figured id ask. I am going the gulp route but can take care of the less -> sass port and then just take the gulp piece on in my project, rather than pushing it with both.

**Comment by scottmerker** [comment]
@nicholas-b-carter sounds like a plan, thanks for your help!

**Comment by scottmerker** [comment]
@nicholas-b-carter I pulled down your latest from the experimental branch, ran it and it looks pretty good!  Noticed a few minor discrepancies in type sizes, but nothing major.  I'll take a little deeper look later this week, and hopefully @bmathews can chime in as well.  Thanks for your contribution, this is a big win for the library.

**Comment by nicholas-b-carter** [comment]
@scottmerker, I realized why those discrepancies exist. Apparently the way sass deals with variable assignment is different from less to sass so the usptostrap variables had to be refactored/reordered. I have completed this and am going to issue an additional PR that will correct this. Can you verify once it's issued?

**Comment by nicholas-b-carter** [comment]
@SCOTTMERKER, also, I finished the gulp es6 automation and added gulp github pages as well to automate the publishing of the library if interested?

**Comment by scottmerker** [comment]
Sure, if you want to do a pull request into the experimental branch i'll add it!

**Comment by scottmerker** [comment]
@nicholas-b-carter - Nick, how easy do you think it would be to fold the SASS port into the bootstrap 4 alpha?  Do you have any experience with the latest version?

**Comment by nicholas-b-carter** [comment]
@scottmerker, Hey Scott sorry for the delay in getting the updates pushed i have been interviewing to move out of state. I will push the updates to the repo later this afternoon. 

As far as folding the SASS port into bootstrap4 alpha it should be really easy after I push the update to address the variable injection. The bootstrap version that I used as part of the port is the official bootstrap3-sass release which is already structured the same was as the bootstrap4 library. The only changes that are required are to the _variables.scss file and some basic syntax updates. When I was in the process of doing the port I found out that the issue was related to the way less and sass variable replacement happens. In LESS the replacement happens after all of the require statements have been executed which allow you to require overrides to the existing bootstrap less library ie; uspto/variables.less. However, in SASS i found out that the variable replacement happens once the require statement is executed. Because of this I had to refactor the variables file to include all of the variables referenced in bootstraps variables file and apply the overrides + additional variable definitions in there, so they are available for the rest of the files to reference. 

This is the change I will be pushing later this afternoon. So, aside from that the only other difference would be that bootstrap4 is based on flexbox and that they have changed some of the syntax around existing bootstrap components. Pretty basic, they have outlines them here: http://bootstrap4.guide/ and there is a conversion tool available at: http://upgrade-bootstrap.bootply.com/ - this outlines the changes in classes as well as a conversion tool to convert bs3 html to bs4. 

Hopefully this helps?


Thanks,
Nick

**Comment by scottmerker** [comment]
Thanks @nicholas-b-carter !

I pulled the latest in, and only briefly had a chance to look at it. Looks like good progress!  Saw an error with the image processing, but that might be on my end (i'll have to look).

Eagerly waiting for 4.0 to come out of alpha so we can seriously take a look at it.

**Comment by nicholas-b-carter** [comment]
sure @scottmerker, I already have the gulp, gh-pages, sass port completed.
Quite a bit faster I can share that if you'd like?

Could swap out bs3sass to bs4.

**Comment by scottmerker** [comment]
@nicholas-b-carter  - If you want to pull it into the experimental, why not?!

**Comment by nicholas-b-carter** [comment]
@scottmerker, would you prefer another branch. Just don't want to disrupt
current architecture.

**Comment by scottmerker** [comment]
@nicholas-b-carter Sent you an invite for a new repo.  Let's move the development over there and see what sort of rabbit holes we go down.

**Comment by scottmerker** [comment]
@nicholas-b-carter Just checking in with you.. did you receive the invite for the new repo?

**Comment by nicholas-b-carter** [comment]
@scottmerker, yeah sorry for the delay I have been packing and everything else. Trying to get everything together before I move next week. I'll have some time tomorrow to get things rolling.

Thanks,
Nick

**Comment by three60five** [comment]
I'd like to take a peak at this repo with the port of the USPTO libary to sass built with gulp. Where is it?

**Comment by scottmerker** [comment]
Sass integrated into main REPO, see build notes.  Closing until we revisit with version 2.0.
