### ISSUE TITLE
Wrong version in v1.4.1, v1.4.3, v1.4.4, v1.5.0

### ISSUE THREAD

**Issue by travisperson** [USPTO/designpatterns#142]
I noticed that the following tags do not have the proper version in their `package.json`

* v1.4.1
* v1.4.3
* v1.4.4
* v1.5.0

**Comment by scottmerker** [comment]
Thanks @travisperson, great catch.  File has been updated.  Need to look into having that automatically updated when we do a release so it stays current (and doesn't get overlooked).
