### ISSUE TITLE
Styled checkboxes and radio buttons

### ISSUE THREAD

**Issue by AaronUXD** [USPTO/designpatterns#153]
Styling these two controls makes it easier to see what is selected and provides a larger visual target for touch. We could copy the two controls from: https://standards.usa.gov/form-controls/

![image](https://cloud.githubusercontent.com/assets/9051299/17333716/6a72ff1e-58a1-11e6-992d-f6be9e26535b.png)

![image](https://cloud.githubusercontent.com/assets/9051299/17333729/7ae4564a-58a1-11e6-8fbc-e6355f596deb.png)

**Comment by scottmerker** [comment]
@AaronUXD I've tagged this with v2.  I think this warrants a discussion.  This is pretty easily achievable with font-awesome, but for v1.x we aren't fully supporting that font icon set.  Emulating this in SVG might be a nightmare.

**Comment by bmathews** [comment]
SVGs inlined into the CSS as `url(data...` _could_ work if you wanted it in v1.x. The usa.gov example above is loading an external svg.

**Comment by scottmerker** [comment]
Framework and beta examples added for this in pull #185.
