### ISSUE TITLE
Depreciated vs. deprecated

### ISSUE THREAD

**Issue by lincolngup** [USPTO/designpatterns#156]
I found a possible terminology oddity. The following section uses the word "depreciated" where "deprecated" is the term I've always associated with the retirement of software language elements. They're similar in meaning, but in my experience, "deprecated" may be more correct.
http://uspto.github.io/designpatterns/docs/patterns/dataFormats.html#depreciated

**Comment by scottmerker** [comment]
@lincolngup - do you want to update?

**Comment by lincolngup** [comment]
Yes. I'll contact you for hints on getting my dev env up and running.

**Comment by scottmerker** [comment]
Updated in latest patch.
