### ISSUE TITLE
increase/decrease icon size

### ISSUE THREAD

**Issue by AaronUXD** [USPTO/designpatterns#158]
How do you control the size of the svg icons we are using? e.g. to make the loading-icon half the size or twice as big?

`<span class="icon loading-icon"></span>`

http://uspto.github.io/designpatterns/docs/foundation/icons.html

**Comment by scottmerker** [comment]
@AaronUXD - While not the best implementation, icons can be scaled by wrapping in a DIV with the following style = transform: scale(1.5) , replacing the 1.5 with whatever scale you prefer.  For example "transform: scale(2) would be double scale from original.

This can be best seen in action on the page here - http://uspto.github.io/designpatterns/docs/inspiration/marketing.html

I'm hoping we can move away from SVG in the future.

**Comment by AaronUXD** [comment]
@scottmerker - that seems to make it blur in our IE browser without some additions.

Have we considered base64 @font-face?

http://sosweetcreative.com/2613/font-face-and-base64-data-uri

perhaps that would meet our needs

**Comment by AaronUXD** [comment]
nm, appears that base64 won't work in our situation either.
