### ISSUE TITLE
Improve filters pattern and examples

### ISSUE THREAD

**Issue by AaronUXD** [USPTO/designpatterns#16]
will it be clear which filters are currently applied with a long side list? May want to consider having current filters listed across top? not sure...

For top filters, how did they select two conveyance types? (assuming its a drop down)

**Comment by scottmerker** [comment]
Closing old issue; Latest filters available here http://uspto.github.io/designpatterns/1.x/docs/patterns/filters.html and http://uspto.github.io/designpatterns/1.x/docs/inspiration/search-results.html for inspiration.
