### ISSUE TITLE
Using designpatterns in a node project

### ISSUE THREAD

**Issue by Buckminsterfullerene** [USPTO/designpatterns#179]
Hello Design Pattern team.  We are using the design pattern library in several node projects.  We are using the LESS files that you provide, however, we get errors during our builds that pertain to the reference @bootstrap-path: "bootstrap/"; in the usptostrap.less file.  This is because there is no 'bootstrap' folder at that location.  

Would it be alright to have one of these options?

- Include the bootstrap folder in the designpatterns project.

- Have the reference, @bootstrap-path, point to something like "../../../bower_components/bootstrap/..."

Here's how we currently use designpatterns in our project.  We have a LESS file that imports USPTOPatternLibrary/usptostrap/less/usptostrap.less.  When we run our build the LESS compiler fails on the reference to bootstrap.

(LOG Output from Grunt)
-----------------------------------
Running "less:dev" (less) task
>> FileError: 'bootstrap//less/utilities.less' wasn't found. Tried - bower_components\USPTOPatternLibrary\usptostrap\less\bootstrap\less\utilities.less,app\styles\bootstrap\less\utilities.less,bootstrap\less\utilities.less in bower_components\USPTOPatternLibrary\usptostrap\less\_utilities.less on line 1, column 1:
>> 1 @import "@{bootstrap-path}/less/utilities";
>> 2

Any help would be great.  Thanks much.

**Comment by bmathews** [comment]
Hi there! 

You have two options:

1) Add the `bower_components` dir to your LESS import paths option. This will look for the 'bootstrap' dir in there. https://github.com/gruntjs/grunt-contrib-less#paths
2) Override the `@bootstrap-path` variable before importing `usptostrap.less` into your project. E.g.,
```
@bootstrap-path: '../../../bower_components/bootstrap/...';
@import 'path/to/usptostrap.less';
```

Let us know if either of those work options work for you or not.

**Comment by Buckminsterfullerene** [comment]
Thanks @bmathews for the quick reply.  The two options will not work, unfortunately.  We will continue with our current process of handling the issue by configuring our Grunt to modify the usptostrap.less file.

Thanks for your time and having a great project!  It's well done.
