### ISSUE TITLE
Missing SVG file

### ISSUE THREAD

**Issue by AlanPTO** [USPTO/designpatterns#189]
Beginning in 1.5.3 there is a call in the compiled CSS which is looking for 'sprite.svg'. This is not included in the repository and causes build failures. Can you push the file or have it removed?

**Comment by scottmerker** [comment]
@AlanPTO  - We fixed this issue last week in merge #188 , if you grab the latest from the source it should be fixed (it hasn't been rolled into an official version yet though).

Let me know if it is still giving you issues.

**Comment by AlanPTO** [comment]
Thanks.
