### ISSUE TITLE
Sized up icons in IE 10+

### ISSUE THREAD

**Issue by Department-of-Commerce-OIG** [USPTO/designpatterns#196]
I just viewed the pattern library icon page (http://uspto.github.io/designpatterns/1.x/docs/foundation/icons.html) in the newest Internet Explorer for the first time. The resolution of the SVG when scaled is pixelating:
![image](https://user-images.githubusercontent.com/31544235/30926067-fd48d21a-a381-11e7-80dd-ee32e09e01e1.png)

**Comment by scottmerker** [comment]
@Department-of-Commerce-OIG - We're actively working on a fix for that specific IE issue, and it should hopefully be available in the next release.

**Comment by scottmerker** [comment]
@Department-of-Commerce-OIG - We are now recommending using the latest Font Awesome 5 implementation to get this functionality, and we have added that to the library.
