### ISSUE TITLE
select2 defects

### ISSUE THREAD

**Issue by arvalarva** [USPTO/designpatterns#198]
I've been trying to figure out the problem with the form dropdowns and I can't pinpoint it, yet. Thought I'd open an issue, instead, in case someone smarter and wiser can find the problems. There's a thin border around the closed dropdown, and the open dropdown has a disconnected right-side border. 
![image](https://user-images.githubusercontent.com/8140814/33972528-3c8e6d70-e04c-11e7-98a1-a299d649078c.png)

**Comment by scottmerker** [comment]
@arvalarva - This has been repaired in v1.6.2,  the code that was conflicting was removed.
