### ISSUE TITLE
Alerts and notifications issues

### ISSUE THREAD

**Issue by jjohnson10** [USPTO/designpatterns#200]
There are two issues to correct regarding alerts and notifications.

**Issue 1:** Not enough time to review alerts and notfications before timing out. As per W3C Recommendations for Guideline 2.2 Enough Time: Provide users enough time to read and use content. (https://www.w3.org/TR/2008/REC-WCAG20-20081211/#time-limits-required-behaviors) users need at least 20 seconds to read any auto dismissing alert and notification messages. Currently the stated behavior is 5 seconds. See http://uspto.github.io/designpatterns/docs/components/alerts.html.

**Issue 2:** The close button for alert and notification messages is not passing 508 requirement of at least 4.5:1 color contrast. Recommend updating the close button icon and change the color #444. 

Close icon should be updated to: 
![image](https://user-images.githubusercontent.com/35149861/34626338-3f550d30-f22a-11e7-832e-4467a8905e9c.png)

**Comment by scottmerker** [comment]
@jjohnson10 - This has been resolved in v1.6.2 - The current styles use opacities versus a specific color, but those values have been increased in both the less and sass files.
