### ISSUE TITLE
Modals

### ISSUE THREAD

**Issue by arvalarva** [USPTO/designpatterns#201]
Need modal pattern.

Recommend follow Bootstrap 4:
[https://getbootstrap.com/docs/4.0/components/modal/](url)

**Comment by bmathews** [comment]
Does the existing dialog pattern not cover it? There's a "Show Modal" button at the bottom: http://uspto.github.io/designpatterns/1.x/docs/components/dialogs.html

**Comment by arvalarva** [comment]
Thanks, Brian. You’re right. Looks like we’ve got a typo.

**Comment by arvalarva** [comment]
Closing this issue since the modals are there and making a pull request to fix typos and return heading "Modal"
