### ISSUE TITLE
Need to reduce gap between label and value in Metadata pattern 

### ISSUE THREAD

**Issue by kdhanesha** [USPTO/designpatterns#206]
The gap betweenI label and value in Metadata is a bit too much. suggest reducing the gap by 5-10 pixels or if using relative sizing, 2 character width.

The pattern can be found at http://uspto.github.io/designpatterns/1.x/docs/components/metadata.html

A screen shot of existing pattern is attached here.
![label value pair issue reported by kd](https://user-images.githubusercontent.com/9576508/39834623-94e1fc04-539b-11e8-86bb-e1405b22f6fb.PNG)

**Comment by scottmerker** [comment]
Updated in v1.6.4
