### ISSUE TITLE
_type.less file has SASS code

### ISSUE THREAD

**Issue by Buckminsterfullerene** [USPTO/designpatterns#210]
The file, **_type.less**, has SASS code which breaks front-end builds for projects using Angular 6.1.* with Angular CLI 6.1.*.

We have temporarily fixed the problem by changing the line `@extend .clearfix();` to `&:extend(.clearfix);` within our project.

Will it be possible to have this fixed?

Thanks!

**Comment by scottmerker** [comment]
@Buckminsterfullerene - Patch has been added.  Thanks for the heads up!
