### ISSUE TITLE
Alerts/Notifications info icon and action buttons

### ISSUE THREAD

**Issue by arvalarva** [USPTO/designpatterns#26]
Can we try putting the "undo" link within the notification in a frame of sorts? Perhaps in a little button? I'm worried that longer notification text will run into it and make it part of the sentence.

Also,can we try the info icon with the circle? If you disagree, it's fine the way it is--whatever you recommend. That may be too close to the error notification, at first glance.

**Comment by scottmerker** [comment]
Completed second half of issue, added footer section for buttons in notifications.
