### ISSUE TITLE
Modal footer guidelines

### ISSUE THREAD

**Issue by davereed** [USPTO/designpatterns#27]
On the modal description it states that the footer should always be visible. The default behavior in bootstrap is to allow the modal to expand vertically and scroll using the main browsers scroll bar. To me, this more usable for users as they don't need to hover or click in to the modal content to begin scrolling. Thoughts?

P.S. if we keep the guideline for the footer always being visible, we will need to update the example modal as it expands off of the page currently when more content is added.

**Comment by scottmerker** [comment]
Closing out this old issue.    If modal is too large, content should scroll; you should never have to scroll to see controls in a modal (it shouldn't expand past 100% of the viewable page).  If the content in a modal needs to scroll, it should be structured in such a way that makes it very clear to a user that there is more content below they might not be seeing. 

*Personal thoughts.. if content in a modal is too extensive to fit: you are trying to fit too much interaction at one time.

**Comment by arvalarva** [comment]
On what viewport are you referring to?

**Comment by scottmerker** [comment]
Any and all.

**Comment by scottmerker** [comment]
Google has some great information regarding this - https://www.google.com/design/spec/components/dialogs.html#dialogs-specs
