### ISSUE TITLE
Additional Short Date Format

### ISSUE THREAD

**Issue by anahitas72** [USPTO/designpatterns#47]
We would like to specify an additional long date format as:  MM/DD/YYYY  

In tables with many dates, for space constraint reasons, it would take up less space to use the above format.

**Comment by bmathews** [comment]
We will add this, thanks!

But, keep in mind that this format does work well for international audiences!

**Comment by bmathews** [comment]
Had a typo in that last response, sorry. I meant: `MM/DD/YYYY` does _not_ work well for international audiences.

For internationally used sites/applications, using it should be discouraged. `MM/DD/YYYY` is indistinguishable from `DD/MM/YYYY`, which is more popular internationally. 

For an international audience, you'd want to use `YYYY/MM/DD` if you need this style of format.

@AaronUXD @arvalarva and others, please feel free to weigh in as well!

**Comment by arvalarva** [comment]
Hi,

Our audience is global, so we do indeed need to  use a format that is usable for everyone. We can’t use MM/DD/YYYY. We should use Brian’s suggestion (and also W3.org’s).

http://www.w3.org/QA/Tips/iso-date

Any objections or considerations?

Thanks,
Arva

**Comment by scottastanton** [comment]
I concur.

**Comment by kdhanesha** [comment]
Will all projects need to move to this format?

What about the users having adjusted to American format? Will it involve a change in how users behave?

Is there any data on usability feedback on proposed format?

Best,
Ketki

**Comment by bmathews** [comment]
Fixd
