### ISSUE TITLE
Font styling

### ISSUE THREAD

**Issue by AaronUXD** [USPTO/designpatterns#53]
Where did the font weights issue leave off? I just attended a demo where the metadata pattern was used and it didn't show any increased weight for the labels.

(update: looks like issue 37 discusses this: https://github.com/USPTO/designpatterns/issues/37 ,but it still isn't working on my laptop. did I not get a uspto wide browser update perhaps or is this an issue for others?)

On my laptop, chrome doesn't show the bolding but in explorer it does. Screen shots below:

![image](https://cloud.githubusercontent.com/assets/9051299/7596480/f2c522d0-f8bb-11e4-8440-50b78572cd0d.png)

![image](https://cloud.githubusercontent.com/assets/9051299/7596489/058255be-f8bc-11e4-9d05-a1b83ce2b59c.png)

**Comment by AaronUXD** [comment]
With the new update to Chrome the semi-bold font is showing up for me now. Is anyone still not seeing semi-bold?

**Comment by bmathews** [comment]
:clap: :clap: :tada:

Thanks for following up on this! From what I could tell, it was a chrome 37 issue only on Windows.

**Comment by scottmerker** [comment]
confirmed working in Chrome 43+ and IE.  Closing.
