### ISSUE TITLE
Additional Wizard Horizontal steps

### ISSUE THREAD

**Issue by MenkaKayan** [USPTO/designpatterns#56]
Brian,

eFile is using a different pattern for the horizontal steps. May we please add that to pattern library.

thanks,
Menka

**Comment by bmathews** [comment]
@MenkaKayan Could you post some screenshots and a writeup of the usage/guidlines on this issue and we can have the UXD team review it? 

Thanks!

**Comment by MenkaKayan** [comment]
![withdraw-wizard](https://cloud.githubusercontent.com/assets/4037433/8233680/9baedf66-15a5-11e5-9c56-81a4ff86a1a5.png)

Usage -
More pronounced visual queue for the user. 

This pattern was added by UCD Lead Ketki.

**Comment by AaronUXD** [comment]
How do you go forward and backward through the steps?

------------------------------------
aaron.pepe@uspto.gov
(571) 272-7185 | MDW 4D30

**Comment by MenkaKayan** [comment]
The steps are not used as navigation.There is a next button that comes in the modal footer, based on the selection made by the user.

**Comment by scottmerker** [comment]
Superseded by issue #76. Closing.
