### ISSUE TITLE
USPTO Patent Search site, a horrendous flaming UI disaster, does not use this style guide!

### ISSUE THREAD

**Issue by jm3** [USPTO/designpatterns#65]
This project is awesome! Thanks for creating it. I'm sad, though, because **The UI Nightmare That Is The USPTO Patent Search website** does not use anything remotely close to this style guide. Instead it features a horror show of UI gaffes, from requiring several clicks to get to a search box, to embedding text in images, using tables everywhere, etc.

So I applaud the creation of this guide — it's clearly needed — but I bemoan its disuse by the USPTO.

Style Guides are great… but running code would be even better. What's the timeframe to implement this guide on USPTO.gov?

![uspto](https://cloud.githubusercontent.com/assets/12213/10152266/41625d7a-6605-11e5-8087-533133291d91.png)

![snippet](https://cloud.githubusercontent.com/assets/12213/10152442/d5f75ea8-6606-11e5-9832-a7f3641d14ab.png)

**Comment by epugh** [comment]
I wish I could *star* this issue, because I had much the same thought when I first ran into PatFT!   

The USPTO is updating their public facing websites.  For example, check out the site that hosts all of China's patents: http://gpsn.uspto.gov, built back in 2013.  Another example is http://assignment.uspto.gov, which is an update of the older site http://assignments.uspto.gov/assignments/q?db=tm.   Or compare http://pairbulkdata.uspto.gov to http://portal.uspto.gov/pair/PublicPair.   

The newer sites make it much easier to access the data in them, whether it's downloading source XML data directly in GPSN, better markup for scaping as done in Assignment, or even bulk data download and API's documented with Swagger (http://pairbulkdata.uspto.gov/swagger/index.html).

**Comment by jm3** [comment]
@epugh cool, that's interesting… but when I go to the **U.S.** PTO, i don't really want to search China's patents, right? I want to search US patents! :) I don't think the majority of US patent searchers care about those other sites — I've never heard of them, and everyone I know just goes to uspto.gov and fumbles around for 5 minutes trying to find the horrible search interface that's been the same since 2008-ish.

The sad sad sad sad thing is, honestly, I or any front-end web developer could fix that search page in less than a day and millions of people would get a better experience immediately, rather than waiting for some ridiculously long update project that never actually lands.

#halfassedadvocacydisguisedasbugreport

Thanks for fighting the good fight! Can we submit PRs to the us gov yet? #kidding #notkidding

**Comment by scottmerker** [comment]
@jm3 @epugh , Are you guys comfortable if I close this issue/non-issue?  We're hoping for a progressively advancing rate of adoption of the pattern library, and a lot of those updates are in progress. Some a little bit slower than others-- but the need is recognized and this pattern library is providing much needed direction towards a unified visual style.

**Comment by jm3** [comment]
@scottmerker respectfully, hope is not a plan. I would have kept the issue open as a reminder that until those main pages get updated, the most important job ain't done from the user's perspective. my recommendation would be: update the main pages, THEN extract those changes into a style guide, and then advocate for its adoption on the secondary pages like the random Chinese ones mentioned above.

but it's your project not mine and you've already closed it, so, good luck I guess.

**Comment by epugh** [comment]
I’m okay with closing the ticket, as I know the USPTO isn’t going to drive their internal dev schedule off of Github tickets!  (Though that would be cool).   I love that this is done through a public repo, and hopefully more reusable assets will be done in a similar fashion.

> On Nov 11, 2015, at 12:04 PM, John Manoogian III <notifications@github.com> wrote:
> 
> @scottmerker <https://github.com/scottmerker> respectfully, hope is not a plan. I would have kept the issue open as a reminder that until those main pages get updated, the most important job ain't done from the user's perspective. my recommendation would be: update the main pages, THEN extract those changes into a style guide, and then advocate for its adoption on the secondary pages like the random Chinese ones mentioned above.
> 
> but it's your project not mine and you've already closed it, so, good luck I guess.
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/USPTO/designpatterns/issues/65#issuecomment-155847527>.
> 

-----------------------------------------------------
Eric Pugh | Principal | OpenSource Connections, LLC | 434.466.1467 | http://www.opensourceconnections.com <http://www.opensourceconnections.com/> | My Free/Busy <http://tinyurl.com/eric-cal>  
Co-Author: Apache Solr Enterprise Search Server, 3rd Ed <https://www.packtpub.com/big-data-and-business-intelligence/apache-solr-enterprise-search-server-third-edition-raw>	
This e-mail and all contents, including attachments, is considered to be Company Confidential unless explicitly stated otherwise, regardless of whether attachments are marked as such.

**Comment by scottmerker** [comment]
@jm3 John, I agree, hope is not a plan; a poor choice of words on my part. As systems are updated, this pattern guide *will* be utilized (it can already be seen on a lot of USPTO services, as well as sits in the coming years).  We've also got a system in place to pull any new ideas back into the repo and make them publicly available for everyone to use.  As directly relates to the PATFT search, I will personally find out when that will be updated and try to give you an timeframe!

@epugh Eric,your github tickets actually do drive changes directly related to the pattern library! But only changes related to the library itself.  Issues and request submissions are taken very seriously, and you can see that a lot (the vast majority) of suggestions submitted here have been rolled into each progressive release. Being public gives anyone an opportunity to fork their own and make changes that can directly impact future product/site releases.  The neat thing: the better this library gets, the more usable systems will become (and the faster they will get released).

**Comment by jm3** [comment]
cool, i look forward to it!

On Thu, Nov 12, 2015 at 4:07 AM, Scott Merker <notifications@github.com>
wrote:

> @jm3 <https://github.com/jm3> John, I agree, hope is not a plan; a poor
> choice of words on my part. As systems are updated, this pattern guide
> *will* be utilized (it can already be seen on a lot of USPTO services, as
> well as sits in the coming years). We've also got a system in place to pull
> any new ideas back into the repo and make them publicly available for
> everyone to use. As directly relates to the PATFT search, I will personally
> find out when that will be updated and try to give you an timeframe!
>
> @epugh <https://github.com/epugh> Eric,your github tickets actually do
> drive changes directly related to the pattern library! But only changes
> related to the library itself. Issues and request submissions are taken
> very seriously, and you can see that a lot (the vast majority) of
> suggestions submitted here have been rolled into each progressive release.
> Being public gives anyone an opportunity to fork their own and make changes
> that can directly impact future product/site releases. The neat thing: the
> better this library gets, the more usable systems will become (and the
> faster they will get released).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/USPTO/designpatterns/issues/65#issuecomment-156086873>
> .
>



-- 

jm3 :: CTO + co-founder, 140 Proof
code.140proof.com

**Comment by scottmerker** [comment]
@jm3 - It doesn't look like updating the patent search site is on any upcoming roadmap I can find.  That's not so say it's not planned..there is a chance the site is being rolled into a whole new product already in development. The need for an update is there, no doubt; it's a really old system.  I'll turn over a few more rocks and see if i can find more info. ;)

**Comment by jm3** [comment]
you rule, thanks!

**Comment by jm3** [comment]
Any updates on this (the style guide being applied to USPTO / TEAS)?
