### ISSUE TITLE
[Suggestion] Update Icon Library to include section for Iconathon icons

### ISSUE THREAD

**Issue by sbeliveau336** [USPTO/designpatterns#68]
The USPTO recently conducted a design workshop to create icons representing intellectual property concepts (http://www.uspto.gov/blog/director/entry/icons_for_intellectual_property_concepts).  These icons are now publically available (https://thenounproject.com/USPTO/collection/uspto-intellectual-property-symbols/).  

Could a new section be created within the Design library icon section to include the icons developed from the iconathon?

Thanks,
-Scott

**Comment by scottmerker** [comment]
Icons have been added, and will be available in the next full release.  Thanks for the suggestion!
