### ISSUE TITLE
panel demo first arrow state incorrect on load

### ISSUE THREAD

**Issue by AaronUXD** [USPTO/designpatterns#92]
for the example, the first arrow shows expanded, but the content isn't expanded. 

http://uspto.github.io/designpatterns/docs/components/collapsiblePanels.html

![image](https://cloud.githubusercontent.com/assets/9051299/11246353/4f7cde00-8de5-11e5-80cc-556bb62ade58.png)

**Comment by scottmerker** [comment]
Repaired, will be included in next patch.
