### ISSUE TITLE
Select element does not receive focus

### ISSUE THREAD

**Issue by vizui** [USPTO/designpatterns#96]
When using the select2 plugin the select element does not receive focus after clicking on its associated label.

Default select element with Bootstrap styling and focus:

![image](https://cloud.githubusercontent.com/assets/3170948/11280116/3e33664a-8ec2-11e5-929b-7a8768d10b1e.png)

Select2 styled select element doesn't receive focus:

![image](https://cloud.githubusercontent.com/assets/3170948/11280127/51998fb6-8ec2-11e5-9867-a19cf569ae2e.png)

Reference:
https://uspto.github.io/designpatterns/1.x/docs/components/formControls.html#select

**Comment by scottmerker** [comment]
@zoinamir - Do you have any sense of what might be happening on with this issue, having extensively used this ;)
